# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseSession(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Session']] = 'Session'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SessionActions[_PrismaModelT]':
        from .client import get_client

        return actions.SessionActions[_PrismaModelT](client or get_client(), cls)


class BaseAccount(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Account']] = 'Account'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AccountActions[_PrismaModelT]':
        from .client import get_client

        return actions.AccountActions[_PrismaModelT](client or get_client(), cls)


class BaseVerification(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Verification']] = 'Verification'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.VerificationActions[_PrismaModelT]':
        from .client import get_client

        return actions.VerificationActions[_PrismaModelT](client or get_client(), cls)


class BaseSearch(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Search']] = 'Search'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SearchActions[_PrismaModelT]':
        from .client import get_client

        return actions.SearchActions[_PrismaModelT](client or get_client(), cls)


class BaseArticle(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Article']] = 'Article'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ArticleActions[_PrismaModelT]':
        from .client import get_client

        return actions.ArticleActions[_PrismaModelT](client or get_client(), cls)


class BaseInsight(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Insight']] = 'Insight'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.InsightActions[_PrismaModelT]':
        from .client import get_client

        return actions.InsightActions[_PrismaModelT](client or get_client(), cls)


class BaseClaim(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Claim']] = 'Claim'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ClaimActions[_PrismaModelT]':
        from .client import get_client

        return actions.ClaimActions[_PrismaModelT](client or get_client(), cls)


class BaseEvidence(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Evidence']] = 'Evidence'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.EvidenceActions[_PrismaModelT]':
        from .client import get_client

        return actions.EvidenceActions[_PrismaModelT](client or get_client(), cls)


class BaseEvent(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Event']] = 'Event'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.EventActions[_PrismaModelT]':
        from .client import get_client

        return actions.EventActions[_PrismaModelT](client or get_client(), cls)


class BaseClaimCluster(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ClaimCluster']] = 'ClaimCluster'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ClaimClusterActions[_PrismaModelT]':
        from .client import get_client

        return actions.ClaimClusterActions[_PrismaModelT](client or get_client(), cls)


class BaseLLMCache(_PrismaModel):
    __prisma_model__: ClassVar[Literal['LLMCache']] = 'LLMCache'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.LLMCacheActions[_PrismaModelT]':
        from .client import get_client

        return actions.LLMCacheActions[_PrismaModelT](client or get_client(), cls)


class BaseLLMUsage(_PrismaModel):
    __prisma_model__: ClassVar[Literal['LLMUsage']] = 'LLMUsage'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.LLMUsageActions[_PrismaModelT]':
        from .client import get_client

        return actions.LLMUsageActions[_PrismaModelT](client or get_client(), cls)


class BaseConsensusFact(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ConsensusFact']] = 'ConsensusFact'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ConsensusFactActions[_PrismaModelT]':
        from .client import get_client

        return actions.ConsensusFactActions[_PrismaModelT](client or get_client(), cls)


class BaseContradictionPair(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ContradictionPair']] = 'ContradictionPair'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ContradictionPairActions[_PrismaModelT]':
        from .client import get_client

        return actions.ContradictionPairActions[_PrismaModelT](client or get_client(), cls)


