from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Session',
    'Account',
    'Verification',
    'Search',
    'Article',
    'Insight',
    'Claim',
    'Evidence',
    'Event',
    'ClaimCluster',
    'LLMCache',
    'LLMUsage',
    'DemoSnapshot',
    'TopicSubscription',
    'TopicSnapshot',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'sessions': 'Session',
        'accounts': 'Account',
        'searches': 'Search',
        'subscriptions': 'TopicSubscription',
    },
    'Session': {
        'user': 'User',
    },
    'Account': {
        'user': 'User',
    },
    'Verification': {
    },
    'Search': {
        'user': 'User',
        'articles': 'Article',
        'insights': 'Insight',
    },
    'Article': {
        'search': 'Search',
        'evidence': 'Evidence',
    },
    'Insight': {
        'search': 'Search',
    },
    'Claim': {
        'cluster': 'ClaimCluster',
        'evidence': 'Evidence',
    },
    'Evidence': {
        'claim': 'Claim',
        'article': 'Article',
    },
    'Event': {
        'claimClusters': 'ClaimCluster',
    },
    'ClaimCluster': {
        'event': 'Event',
        'claims': 'Claim',
    },
    'LLMCache': {
    },
    'LLMUsage': {
    },
    'DemoSnapshot': {
    },
    'TopicSubscription': {
        'user': 'User',
        'snapshots': 'TopicSnapshot',
    },
    'TopicSnapshot': {
        'subscription': 'TopicSubscription',
    },
}

# fmt: on